spring:
  datasource:
    url: jdbc:mysql://localhost:3310/review_db
    username: user
    password: b12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
